# Run on 00:00 every Monday
# Upgrade package-lock.json then git push

name: Package upgrade

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1'

permissions:
  contents: write

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: upgrade with npm i
        run: npm i
      - name: Commit package-lock.json
        run: |
          git config --global user.name 'Upgrade Bot'
          git config --global user.email 'db-man-upgrade-bot@users.noreply.github.com'
          # git commit -am "npm i"
          # git push
          git diff --quiet && git diff --staged --quiet || git commit -am 'npm i'
